USE [master]
GO
CREATE LOGIN [pis] WITH PASSWORD=N'xMgk34_c23f98AL!', DEFAULT_DATABASE=[PIS], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO


USE [master]
GO
CREATE LOGIN [pis] WITH PASSWORD=N'xMgk34_c23f98AL!', DEFAULT_DATABASE=[PIS], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
USE [PIS]
GO
CREATE USER [pis] FOR LOGIN [pis]
GO
USE [PIS]
GO
ALTER ROLE [db_owner] ADD MEMBER [pis]
GO